name: Notify Infra on Release

on:
  release:
    types: [published]

jobs:
  notify-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Notify infra repo
        run: |
          curl -X POST https://api.github.com/repos/dingjunyu888/final-devops-infra/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            -d '{
              "event_type": "trigger-uat-deploy",
              "client_payload": {
                "tag": "${{ github.event.release.tag_name }}"
              }
            }'
